### ISSUE TITLE
Villagers give op EcoEnchants items

### ISSUE THREAD

**Issue by Dthen** [Dthen/CubeCraft#1]
Villager trades give OP enchanted books.

Config (located at `/EcoEnchants/rarity.yml` file looks like this:
```
rarities:
  common:
    table-probability: 20
    minimum-level: 1
    villager-probability: 10.5
    loot-probability: 12
    custom-color:
      enabled: false
      color: '&7'
  uncommon:
    table-probability: 10
    minimum-level: 5
    villager-probability: 6
    loot-probability: 16
    custom-color:
      enabled: false
      color: '&a'
  rare:
    table-probability: 10
    minimum-level: 15
    loot-probability: 2.5
    custom-color:
      enabled: false
      color: '&9'
    villager-probability: 7.5
  epic:
    table-probability: 5
    minimum-level: 16
    villager-probability: 2
    loot-probability: 6
    custom-color:
      enabled: false
      color: '&5'
  legendary:
    table-probability: 4
    minimum-level: 20
    villager-probability: 2
    loot-probability: 1
    custom-color:
      enabled: false
      color: '&6'
  special:
    table-probability: 2
    minimum-level: 30
    villager-probability: 3
    loot-probability: 5
    custom-color:
      enabled: false
      color: '&d'
  veryspecial:
    table-probability: 1
    minimum-level: 30
    villager-probability: 1.5
    loot-probability: 2
    custom-color:
      enabled: false
      color: '&4'
```

So as you can see it's fairly easy to change, but I'm not doing it right this second, this is a distraction from what I was doing previously. Should be an easy fix, just not doing it rn, writing it down so I remember.
